### ISSUE TITLE
Track Data after successful CONNECT

### ISSUE THREAD

**Issue by cstayyab** [fmoo/twisted-connect-proxy#13]
In HTTPS when connection has established, Is there any method (here or in twisted library) to track the content of each request and its response? I have sucessfully done it for HTTP but when an HTTPS website is connected the data is not passing through that mehtod (ProxyClient.handleReponsePart() in twisted/web/proxy.py) but same method is not handling the HTTPS connections. 

Any hint or help will be appreciated.

**Comment by fmoo** [comment]
It's not possible the way this server and modern browsers are implemented. 

For you to MITM SSL you'd have to be trusted by the client and forge certificates on the fly; even then, most browsers pin certificates for popular sites and would reject yours.

If you had a custom browser installed on the clients you could configure it to use GET instead of CONNECT for https queries or just disable cert pinning so cert forging would work, but at that point you might as well just install a browser extension that monitors all site traffic. 

If you don't have access to the clients and are ok not inspecting the payloads and just knowing more about the sites, you might be able to take advantage of plaintext SNI headers in TLS, but as SNI encryption in TLS 1.3 rolls out you'd be screwed there.

The "best" thing you could do at that point is build up a profile of traffic by IP, but third party CDNs is difficult / will be impossible to attribute specific payloads for.

**Comment by fmoo** [comment]
That said if you wanted to just track or record all the encrypted data, I guess that's pretty easy to do with this, but has really limited utility.

You'd have to break the encryption though if you wanted to see the actual requests and traffic.

**Comment by cstayyab** [comment]
Okay. Thank you for the explanation. I dropped this idea and made my app with a different implementation using Twisted Web Server.

Regards.
